name: Infra
description: 
title: "[INFRA]: "
labels: ["infra"]
assignees:
  - hank-dev-ats
body:
  - type: markdown
    attributes:
      value: |
        ###  :heavy_check_mark: 안내
        - 프로젝트를 선택하고, DueDate, Priority 를 설정해주세요.

  - type: input
    id: envoriment
    attributes:
      label: envoriment
      description: 인프라 환경을 적어주세요.
      placeholder: ex. AWS, DB, Github actions 등
    validations:
      required: true
  - type: input
    id: why
    attributes:
      label: Purpose
      description: 요청 이유를 적어주세요.
      placeholder: 운영성 업무를 위한 XX 테이블 update 권한 요청
    validations:
      required: false
