name: 3. Bug
description: 버그, 오류 등 비정상적인 동작에 대한 이슈
title: "[BUG]: "
labels: ["bug"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        ###  :heavy_check_mark: 안내
        - 프로젝트를 선택하고, DueDate, Priority 를 설정해주세요.
        - 이슈에 해당하는 라벨링을 해주세요.
        - 자세한 설명은 버그를 잡는데 도움이 됩니다. :innocent:

  - type: dropdown
    id: enviorment
    attributes:
      label: Enviorment
      description: 실행 환경을 선택해주세요. (다중 선택 가능)
      multiple: true
      options:
        - iOS
        - Android
        - Chrome
        - Safari
        - Etc
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: 버전 정보를 입력해주세요.
      placeholder: ex. v.1.0.0
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date
      description: 버그가 발생한 날짜, 시간을 알려주세요.
      placeholder: ex. 2022-11-01 화요일 오후 2시 30분경
    validations:
      required: false
  - type: input
    id: account
    attributes:
      label: Account Infomation
      description: 버그가 발생한 계정 정보를 알려주세요.
      placeholder: ex. hank@artinus.dev or 010-1234-5678 or 접속정보 불필요 or -
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Content
      description: 최대한 상세하게 작성해주세요. 스크린샷이 있으면 더 좋습니다.
      placeholder: 최대한 상세하게 작성해주세요.
    validations:
      required: true
