name: Etc
description: 기타 관련 업무
title: "[기타]: "
labels: ["ETC"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        ###  :heavy_check_mark: 안내
        - 프로젝트를 선택하고, DueDate, Priority 를 설정해주세요.
        - 이슈에 해당하는 라벨링을 해주세요.

  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: 자유롭게 작성해주세요.
    validations:
      required: true

