name: management
description: 상품, 푸시, 공지사항 등 운영 관련 업무
title: "[Management]: "
labels: ["management"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        ###  :heavy_check_mark: 안내
        - 프로젝트를 선택하고, DueDate, Priority 를 설정해주세요.
        - 이슈에 해당하는 라벨링을 해주세요.
        - 상세한 요구사항은 데이터를 추출 및 운영에 도움이 됩니다. :innocent: 
        #
        
  - type: dropdown
    id: privacy
    attributes:
      label: Management Type
      options:
        - 상품 
        - 앱 푸시
        - 공지사항
        - 이미지 
        - 기타 
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: 요구사항을 작성해주세요.
    validations:
      required: true
