name: SQL
description: 데이터 추출 및 운영 관련 이슈
title: "[SQL]: "
labels: ["SQL"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        ###  :heavy_check_mark: 안내
        - 프로젝트를 선택하고, DueDate, Priority 를 설정해주세요.
        - 이슈에 해당하는 라벨링을 해주세요.
        - 상세한 요구사항은 데이터를 추출 및 운영에 도움이 됩니다. :innocent: 

        ### ❗ 개인정보 업무 프로세스 
        1. issuer : 이슈 등록 및 협의
        2. assignee : 데이터 추출 및 암호화하여 comment 첨부.
        3. assignee : 비밀번호 slack 또는 개별 전달.
        4. issuer : 업무 목적 완료 후 완전 파기하고 추가 comment 작성.
        5. assignee : 첨부 파일 삭제 후 이슈 close  
        #
        
  - type: dropdown
    id: privacy
    attributes:
      label: Privacy
      description: 개인정보 포함 여부를 선택하세요.
      options:
        - 포함 - 목적 완료 후 개인정보를 반드시 파기합니다.
        - 미포함
    validations:
      required: true
  - type: input
    id: purpose
    attributes:
      label: Purpose
      description: 간략한 목적을 입력해 주세요.
      placeholder: ex. 첫번째 작품 이벤트 대상자 추첨을 위함
    validations:
      required: true
  - type: input
    id: range
    attributes:
      label: Date
      description: 기간을 자유로운 형식으로 입력해 주세요.
      placeholder: ex. 2022-10-01 ~ 2022-10-07
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: 데이터 기준을 명확하게 작성해 주세요. 
      placeholder: 최대한 상세하게 작성해 주세요.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected results
      description: 예상하는 데이터 결과를 알려주세요.
      render: shell
    validations:
      required: true
