name: SQL
description: 데이터 추출 및 운영 관련 이슈
title: "[SQL]: "
labels: ["SQL"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        상세한 요구사항은 데이터를 추출 및 운영하는데 도움이 됩니다. :innocent:
  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy
      description: 개인정보가 포함된 데이터 추출은 체크하고, 개인정보 label을 추가해주세요.
      options:
        - label: 개인정보가 포함되어 있습니다. 목적 완료 후 개인정보를 파기합니다.
  - type: dropdown
    id: privacy
    attributes:
      label: 개인정보
      description: 개인정보 포함 여부를 선택하고, 개인정보 label을 추가해주세요. 목적 완료 후 개인정보를 반드시 파기해야 합니다.
      options:
        - 포함
        - 미포함
    validations:
      required: true
  - type: input
    id: objective
    attributes:
      label: 목적
      placeholder: ex. 첫번째 작품 이벤트 대상자 추첨을 위함
    validations:
      required: true
  - type: input
    id: range
    attributes:
      label: 기간
      placeholder: ex. 2022-10-01 ~ 2022-10-07
  - type: textarea
    id: what-happened
    attributes:
      label: Content
      description: 데이터 기준을 명확하게 작성해주세요. 
      placeholder: 최대한 상세하게 작성해주세요.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected outcomes
      description: 예상하는 데이터 결과에 대해 작성해주세요.
      render: shell
    validations:
      required: true
